### ISSUE TITLE
HMI files

### ISSUE THREAD

**Issue by maukcc** [iworld4us/nextion-2.4#2] opened 2018-05-16 12:28 UTC
Can you add the HMI files for the 2.4 and 2.8 and 3.2 displays?
Much appreciated !

**Comment by iworld4us** [comment] 2018-05-17 17:07
https://github.com/iworld4us/nextion-2.4

**Comment by maukcc** [comment] 2018-05-18 09:32
Thank you for your response.
We can see the .tft files, but not the .HMI editor files

**Comment by iworld4us** [comment] 2018-07-25 18:39
Duplicate of #1.

**Closed as completed by iworld4us** 2018-07-25 18:39 UTC
